#!/bin/bash

        echo "Beginne die Datei mainforKListener.cpp und die Dateien USSensor.cpp, steuerung.cpp zu compilern"
        g++ -Wall -pedantic mainforKListener.cpp ./Motorsteuerung/steuerung.cpp ./USSensor/USSensor.cpp -o MainKListener -lwiringPi -lpthread
        echo "mainforKListener.cpp Compiliert -> Ausgabedatei = MainKListener"
